version: '3.8'

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    networks:
      - app-network

  api:
    build: .
    container_name: math-api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://admin:admin123@mongo:27017
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
